update hiprand header path (#3252)
Need to update hiprand header path to "<hiprand/hiprand.hpp>" so it
will work with future rocm release. It will work with 5.4 release too.
So to be ready well ahead with future rocm changes, requesting the
change,

In file included from
/home/master/amr-wind/submods/amrex/Src/Base/AMReX_RandomEngine.H:11:
/opt/rocm-xxxx/include/hiprand.hpp:16:2: error: "This file is
deprecated. Use the header file from
/opt/rocm-xxx/include/hiprand/hiprand.hpp by using #include
<hiprand/hiprand.hpp>"
#error "This file is deprecated. Use the header file from
/opt/rocm-xxxx/include/hiprand/hiprand.hpp by using #include
<hiprand/hiprand.hpp>"
 ^

The proposed changes: It will help user to be ready to use future rocm
release alongwith previous releases like 5.4.